import type {SiteConfig,Section} from '../types/site';
export function PublicSite({config,onAdmin}:{config:SiteConfig;onAdmin:()=>void}){const enabled=(id:string)=>config.sections.find(s=>s.id===id)?.enabled;return <div className="site" style={{'--primary':config.theme.primary,'--secondary':config.theme.secondary,'--ink':config.theme.ink,'--paper':config.theme.paper,'--grey':config.theme.grey,'--accent':config.theme.accent,'--dark':config.theme.dark} as React.CSSProperties}>
<nav className="nav"><a className="brand" href="#">{config.brand.name}</a><div className="navlinks">{config.nav.map(n=><a key={n.href} href={n.href}>{n.label}</a>)}<a className="navcta" href="#cta">Get started</a></div></nav>
{enabled('hero')&&<section className="hero"><div><span className="eyebrow">{config.hero.eyebrow}</span><h1>{config.hero.title}</h1><p>{config.hero.subtitle}</p><div className="buttons"><a className="primary" href="#cta">{config.hero.primaryCta}</a><a className="outline" href="#steps">{config.hero.secondaryCta}</a></div></div></section>}
{enabled('stats')&&<section className="stats">{config.stats.map(s=><div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</section>}
{enabled('steps')&&<section id="steps" className="section"><Header eyebrow="The process" title="Three steps. Zero friction."/><div className="stepgrid">{config.steps.map(s=><article className="card" key={s.title}><b>{s.icon}</b><h3>{s.title}</h3><p>{s.body}</p></article>)}</div></section>}
{enabled('ticker')&&<section className="ticker">{config.findings.map(f=><div key={f.finding}><small>{f.category}</small><span>{f.finding}</span><em className={f.status}>{f.statusText}</em></div>)}</section>}
{enabled('report')&&<section className="section soft"><Header eyebrow="Preview" title={config.report.title}/><div className="report"><h3>{config.report.store}</h3><p>{config.report.category}</p><div className="metrics">{config.report.metrics.map(m=><div key={m.label}><strong>{m.value}</strong><span>{m.label}</span></div>)}</div></div></section>}
{enabled('segments')&&<section className="section"><Header eyebrow="Who it's for" title="Built for different kinds of teams."/><div className="three">{config.segments.map(s=><article className="card" key={s.title}><div className="icon"/><h3>{s.title}</h3><p>{s.description}</p><ul>{s.bullets.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></section>}
{enabled('blocks')&&config.blocks.map((b,i)=><section className={'section block '+b.background} key={i}><div className={'blockgrid '+b.layout}><div><Header eyebrow={b.eyebrow} title={b.title}/><p className="lead">{b.body}</p></div>{b.layout!=='none'&&<div className="visual">{b.image?<img src={b.image}/>:<div className="placeholder">IMAGE / MEDIA</div>}</div>}</div></section>)}
{enabled('articles')&&<Collection id="articles" title={config.articles.heading} subtitle={config.articles.subtitle} items={config.articles.items}/>} 
{enabled('news')&&<Collection id="news" title={config.news.heading} subtitle={config.news.subtitle} items={config.news.items}/>} 
{enabled('people')&&<section id="people" className="section soft"><Header eyebrow="Network" title={config.people.heading}/><p className="lead">{config.people.subtitle}</p><div className="three people">{config.people.items.map(p=><article className="card" key={p.name}><div className="avatar">{p.name.split(' ').map(x=>x[0]).join('')}</div><h3>{p.name}</h3><strong>{p.role}</strong><small>{p.region}</small><p>{p.bio}</p></article>)}</div></section>}
{enabled('philosophy')&&<section className="philosophy"><div><span className="eyebrow">Principle</span><h2>{config.philosophy.title}</h2><p>{config.philosophy.body}</p></div></section>}
{enabled('cta')&&<section id="cta" className="cta"><div><h2>{config.cta.title}</h2><p>{config.cta.body}</p><button onClick={onAdmin}>{config.cta.button}</button></div></section>}
{enabled('footer')&&<footer>{config.footer}<button onClick={onAdmin}>Admin</button></footer>}
</div>}
function Header({eyebrow,title}:{eyebrow:string;title:string}){return <><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></>}
function Collection({id,title,subtitle,items}:{id:string;title:string;subtitle:string;items:{title:string;category:string;excerpt:string;date:string}[]}){return <section id={id} className="section"><Header eyebrow={id==='news'?'Updates':'Insights'} title={title}/><p className="lead">{subtitle}</p><div className="three">{items.map(a=><article className="article" key={a.title}><small>{a.category}</small><h3>{a.title}</h3><p>{a.excerpt}</p><span>{a.date} · Read →</span></article>)}</div></section>}
